
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/sw/ubuntu-22.04/cmake/3.26.4/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 5.15.0-113-generic - x86_64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/u/jnt6mq/.cache/JetBrains/RemoteDev/dist/ce40994fdc0ab_CLion-2024.2.1/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.0-113-generic - x86_64
...
